[package]
name = "protoc-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[build-dependencies]
which = { version = "4", default-features = false }
cfg-if = "1"
cmake = "0.1"

